### ISSUE TITLE
Set Login Text to change while the database is downloading

### ISSUE THREAD

**Issue by jstrojny** [jstrojny/SeniorDesign#10]
Database download takes awhile, text should change to ask the user to wait for it to finish. Maybe make it so it changes every like 10 seconds? Essentially a text progress bar.

**Comment by Sidhwen** [comment]
So I added code for this a while ago, the app throws this : 
I/Choreographer: Skipped 247 frames!  The application may be doing too much work on its main thread.

or some other amount of frames after its done logging in. if we can somehow lessen how much the app is trying to do we could keep the screen updating

**Comment by Sidhwen** [comment]
After a bit of research it seems we have to move the data processing and SQLite Database access into a seperate thread in order for the UI to not be affected

**Comment by jstrojny** [comment]
Closing because this is not feasible in the time we have.
