### ISSUE TITLE
XML Permissions for SQLite Database?

### ISSUE THREAD

**Issue by jstrojny** [jstrojny/SeniorDesign#2]
Database appears to be copying to /data/data/ but is still not readable due to permissions. We are currently looking into this.

**Comment by Sidhwen** [comment]
https://developer.android.com/guide/topics/permissions/requesting.html

this page gives a basic overview of requesting permissions

**Comment by Sidhwen** [comment]
https://developer.android.com/training/permissions/requesting.html

this page gives a java code example for requesting permissions at runtime, which is required for "dangerous" permissions (this includes reading/writing). After API 23 all dangerous permissions are requested at runtime

**Comment by Sidhwen** [comment]
we should probably edit the XML as well as adding a request at runtime (in the main activity?)

**Comment by jstrojny** [comment]
Did we ever update the DB to include an Android_Metadata table? Cause I'm seeing a couple posts mentioning it.
